# Generated by Django 4.2 on 2023-05-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionapp', '0003_alter_answer_image_alter_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
